server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexengrig/microservices-configuration
          search-paths:
            - 'application'
            - 'application/{application}'
            - 'infrastructure'
            - 'infrastructure/{application}'

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
