server:
  port: 8028
  error:
    include-message: ALWAYS

censoring:
  text:
    blacklist:
      - war

spring:
  application:
    name: censoring-text-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
